name: Build Release

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  FIRMWARE_FILENAME: MSRC-RP2040_${{ github.ref_name }}.uf2
  LINK_FILENAME: msrc_link_${{ github.ref_name }}

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:         
  macos:
    runs-on: macos-14

    steps:
      - name: Get actions code
        uses: actions/checkout@v4
        
      - name: Git tags
        run: git fetch --prune --unshallow

      - name: Build
        run: |
          brew install qt
          mkdir build
          cd build
          qmake ../msrc_gui
          make
          mv msrc_gui.app msrc_link_${{ github.ref_name }}.app
          macdeployqt msrc_link_${{ github.ref_name }}.app -dmg
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/msrc_link_${{ github.ref_name }}.dmg
                
      - name: Generate attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: build/msrc_link_${{ github.ref_name }}.dmg
          github-token: ${{ secrets.TOKEN }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: test-app
          path: build/msrc_gui.tgz


